// frontend/src/components/ui/Input.tsx
// Reusable Input components
import React, { forwardRef } from 'react';
import { type LucideIcon } from 'lucide-react';
import { InlineError } from './ErrorDisplay';

export interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {
    label?: string;
    error?: string;
    helpText?: string;
    leftIcon?: LucideIcon;
    rightIcon?: LucideIcon;
    onRightIconClick?: () => void;
    size?: 'sm' | 'md' | 'lg';
    variant?: 'default' | 'filled';
    fullWidth?: boolean;
}

const Input = forwardRef<HTMLInputElement, InputProps>(({
    label,
    error,
    helpText,
    leftIcon: LeftIcon,
    rightIcon: RightIcon,
    onRightIconClick,
    size = 'md',
    variant = 'default',
    fullWidth = true,
    className = '',
    ...props
}, ref) => {
    const sizeClasses = {
        sm: 'px-3 py-2 text-sm',
        md: 'px-3 py-2 text-sm',
        lg: 'px-4 py-3 text-base',
    };

    const variantClasses = {
        default: 'border theme-border-primary theme-bg-primary',
        filled: 'border-0 theme-bg-secondary',
    };

    const baseClasses = 'rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors theme-text-primary';
    const errorClasses = error ? 'border-red-500 focus:ring-red-500' : '';
    const iconPadding = LeftIcon ? 'pl-10' : RightIcon ? 'pr-10' : '';
    const widthClasses = fullWidth ? 'w-full' : '';

    const inputClasses = [
        baseClasses,
        sizeClasses[size],
        variantClasses[variant],
        errorClasses,
        iconPadding,
        widthClasses,
        className,
    ].filter(Boolean).join(' ');

    return (
        <div className={fullWidth ? 'w-full' : ''}>
            {label && (
                <label className="block text-sm font-medium mb-2 theme-text-primary">
                    {label}
                    {props.required && <span className="text-red-500 ml-1">*</span>}
                </label>
            )}
            
            <div className="relative">
                {LeftIcon && (
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <LeftIcon size={18} className="theme-text-tertiary" />
                    </div>
                )}
                
                <input
                    ref={ref}
                    className={inputClasses}
                    {...props}
                />
                
                {RightIcon && (
                    <div className={`absolute inset-y-0 right-0 pr-3 flex items-center ${onRightIconClick ? 'cursor-pointer' : 'pointer-events-none'}`}>
                        <RightIcon 
                            size={18} 
                            className="theme-text-tertiary" 
                            onClick={onRightIconClick}
                        />
                    </div>
                )}
            </div>
            
            {error && <InlineError error={error} />}
            {helpText && !error && (
                <p className="mt-1 text-sm theme-text-tertiary">
                    {helpText}
                </p>
            )}
        </div>
    );
});

Input.displayName = 'Input';


// Select component
export interface SelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> {
    label?: string;
    error?: string;
    helpText?: string;
    options: Array<{ value: string | number; label: string; disabled?: boolean }>;
    placeholder?: string;
    fullWidth?: boolean;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(({
    label,
    error,
    helpText,
    options,
    placeholder,
    fullWidth = true,
    className = '',
    ...props
}, ref) => {
    const baseClasses = 'border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors theme-border-primary theme-bg-primary theme-text-primary';
    const errorClasses = error ? 'border-red-500 focus:ring-red-500' : '';
    const widthClasses = fullWidth ? 'w-full' : '';

    const selectClasses = [
        baseClasses,
        errorClasses,
        widthClasses,
        className,
    ].filter(Boolean).join(' ');

    return (
        <div className={fullWidth ? 'w-full' : ''}>
            {label && (
                <label className="block text-sm font-medium mb-2 theme-text-primary">
                    {label}
                    {props.required && <span className="text-red-500 ml-1">*</span>}
                </label>
            )}
            
            <select
                ref={ref}
                className={selectClasses}
                {...props}
            >
                {placeholder && (
                    <option value="" disabled>
                        {placeholder}
                    </option>
                )}
                {options.map((option) => (
                    <option 
                        key={option.value} 
                        value={option.value}
                        disabled={option.disabled}
                    >
                        {option.label}
                    </option>
                ))}
            </select>
            
            {error && <InlineError error={error} />}
            {helpText && !error && (
                <p className="mt-1 text-sm theme-text-tertiary">
                    {helpText}
                </p>
            )}
        </div>
    );
});

Select.displayName = 'Select';

// Checkbox component
export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
    label?: string;
    error?: string;
    helpText?: string;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(({
    label,
    error,
    helpText,
    className = '',
    ...props
}, ref) => {
    return (
        <div className="flex items-start">
            <div className="flex items-center h-5">
                <input
                    ref={ref}
                    type="checkbox"
                    className={`w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500 theme-border-primary ${className}`}
                    {...props}
                />
            </div>
            {label && (
                <div className="ml-3 text-sm">
                    <label className="font-medium theme-text-primary">
                        {label}
                        {props.required && <span className="text-red-500 ml-1">*</span>}
                    </label>
                    {helpText && !error && (
                        <p className="theme-text-tertiary">
                            {helpText}
                        </p>
                    )}
                    {error && <InlineError error={error} />}
                </div>
            )}
        </div>
    );
});

Checkbox.displayName = 'Checkbox';


export default Input;

// frontend-vue/src/components/ui/Input.vue
<template>
  <div class="relative">
    <!-- Label -->
    <label
      v-if="label"
      :for="inputId"
      class="block text-sm font-medium mb-1"
      :class="labelClasses"
    >
      {{ label }}
      <span
        v-if="required"
        class="text-red-500 ml-1"
        aria-label="required"
      >
        *
      </span>
    </label>

    <!-- Input wrapper -->
    <div class="relative">
      <!-- Left icon -->
      <div
        v-if="leftIcon"
        class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"
      >
        <component
          :is="leftIcon"
          class="h-5 w-5"
          :class="iconClasses"
        />
      </div>

      <!-- Input element -->
      <input
        :id="inputId"
        ref="inputRef"
        :type="inputType"
        :value="modelValue"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        :required="required"
        :maxlength="maxlength"
        :minlength="minlength"
        :pattern="pattern"
        :autocomplete="autocomplete"
        :class="inputClasses"
        @input="handleInput"
        @blur="handleBlur"
        @focus="handleFocus"
        @change="handleChange"
      />

      <!-- Right icon or action -->
      <div
        v-if="rightIcon || clearable"
        class="absolute inset-y-0 right-0 flex items-center"
      >
        <button
          v-if="clearable && modelValue && !disabled && !readonly"
          class="pr-3 text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300 focus:outline-none"
          type="button"
          aria-label="Clear input"
          @click="clearInput"
        >
          <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <div
          v-if="rightIcon && !clearable"
          class="pr-3"
          :class="iconClasses"
        >
          <component :is="rightIcon" class="h-5 w-5" />
        </div>
      </div>
    </div>

    <!-- Helper text -->
    <p
      v-if="helperText && !error"
      class="mt-1 text-sm"
      :class="helperClasses"
    >
      {{ helperText }}
    </p>

    <!-- Error message -->
    <p
      v-if="error"
      class="mt-1 text-sm text-red-600 dark:text-red-400"
    >
      {{ error }}
    </p>

    <!-- Character count -->
    <div
      v-if="showCharacterCount && maxlength"
      class="mt-1 text-xs text-gray-500 dark:text-gray-400 text-right"
    >
      {{ characterCount }}/{{ maxlength }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, nextTick } from 'vue'

type InputType = 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' | 'search'
type InputSize = 'sm' | 'md' | 'lg'

interface Props {
  modelValue: string | number
  type?: InputType
  label?: string
  placeholder?: string
  helperText?: string
  error?: string
  disabled?: boolean
  readonly?: boolean
  required?: boolean
  clearable?: boolean
  showCharacterCount?: boolean
  size?: InputSize
  leftIcon?: typeof import('lucide-vue-next').LucideIcon
  rightIcon?: typeof import('lucide-vue-next').LucideIcon
  maxlength?: number
  minlength?: number
  pattern?: string
  autocomplete?: string
}

const props = withDefaults(defineProps<Props>(), {
  type: 'text',
  label: '',
  placeholder: '',
  helperText: '',
  error: '',
  disabled: false,
  readonly: false,
  required: false,
  clearable: false,
  showCharacterCount: false,
  size: 'md',
  leftIcon: undefined,
  rightIcon: undefined,
  maxlength: undefined,
  minlength: undefined,
  pattern: '',
  autocomplete: '',
})

const emit = defineEmits<{
  'update:modelValue': [value: string | number]
  focus: [event: FocusEvent]
  blur: [event: FocusEvent]
  change: [event: Event]
  clear: []
}>()

const inputRef = ref<HTMLInputElement>()
const inputId = computed(() => `input-${Math.random().toString(36).substr(2, 9)}`)

const inputType = computed(() => {
  // Handle special cases
  if (props.type === 'search') return 'text'
  return props.type
})

const characterCount = computed(() => {
  return String(props.modelValue || '').length
})

const labelClasses = computed(() => {
  return 'text-gray-700 dark:text-gray-300'
})

const inputClasses = computed(() => {
  const classes = []

  // Base classes
  classes.push('block w-full transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed')

  // Size classes
  const sizeClasses = {
    sm: 'px-3 py-2 text-sm',
    md: 'px-3 py-2 text-base',
    lg: 'px-4 py-3 text-lg',
  }

  classes.push(sizeClasses[props.size])

  // Icon padding adjustments
  if (props.leftIcon) {
    const iconPadding = {
      sm: 'pl-10',
      md: 'pl-10',
      lg: 'pl-12',
    }
    classes.push(iconPadding[props.size])
  }

  if (props.rightIcon || props.clearable) {
    const iconPadding = {
      sm: 'pr-10',
      md: 'pr-10',
      lg: 'pr-12',
    }
    classes.push(iconPadding[props.size])
  }

  // State classes
  if (props.error) {
    classes.push('border-red-300 text-red-900 placeholder-red-300 focus:ring-red-500 focus:border-red-500 dark:border-red-600 dark:text-red-100 dark:placeholder-red-400')
  } else if (props.disabled) {
    classes.push('bg-gray-50 border-gray-300 text-gray-500 cursor-not-allowed dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400')
  } else {
    classes.push('border-gray-300 bg-white text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-900 dark:border-gray-600 dark:text-white dark:placeholder-gray-400')
  }

  // Border and background
  classes.push('border rounded-md shadow-sm')

  return classes
})

const iconClasses = computed(() => {
  return props.error
    ? 'text-red-400'
    : props.disabled
    ? 'text-gray-400'
    : 'text-gray-400'
})

const helperClasses = computed(() => {
  return 'text-gray-500 dark:text-gray-400'
})

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement
  let value: string | number = target.value

  // Handle number inputs
  if (props.type === 'number') {
    const numValue = parseFloat(value)
    value = isNaN(numValue) ? 0 : numValue
  }

  emit('update:modelValue', value)
}

function handleBlur(event: FocusEvent) {
  emit('blur', event)
}

function handleFocus(event: FocusEvent) {
  emit('focus', event)
}

function handleChange(event: Event) {
  emit('change', event)
}

function clearInput() {
  emit('update:modelValue', '')
  emit('clear')
  nextTick(() => {
    inputRef.value?.focus()
  })
}

// Expose methods for parent components
defineExpose({
  focus: () => inputRef.value?.focus(),
  blur: () => inputRef.value?.blur(),
  select: () => inputRef.value?.select(),
})
</script>

<style scoped>
/* Additional styles if needed */
</style>
