// frontend-vue/src/components/PerformanceGraphs/components/IOPSComparisonChart.vue
<template>
  <div class="iops-comparison-chart">
    <div class="chart-container" :style="{ height: height + 'px' }">
      <canvas ref="chartCanvas"></canvas>
    </div>

    <!-- Chart Controls -->
    <div class="chart-controls mt-4">
      <div class="flex flex-wrap gap-2">
        <button
          v-for="pattern in availablePatterns"
          :key="pattern"
          :class="[
            'px-3 py-1 rounded-full text-sm transition-colors',
            selectedPatterns.includes(pattern)
              ? 'bg-blue-500 text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600'
          ]"
          @click="togglePattern(pattern)"
        >
          {{ pattern.replace('_', ' ').toUpperCase() }}
        </button>
      </div>
    </div>

    <!-- Chart Stats -->
    <div class="chart-stats mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ maxIOPS.toLocaleString() }}</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Max IOPS</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ avgIOPS.toFixed(0) }}</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Avg IOPS</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ blockSizes.length }}</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Block Sizes</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js'
import { useTheme } from '@/contexts/ThemeContext'
import { processIOPSComparisonData } from '@/utils/chartProcessing'

// Register Chart.js components
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend)

interface Props {
  data: Array<{
    blockSize: string
    patterns: Array<{
      pattern: string
      iops: number | null
    }>
  }>
  height?: number
}

const props = defineProps<Props>()

const { actualTheme } = useTheme()
const chartCanvas = ref<HTMLCanvasElement>()
const chartInstance = ref<ChartJS<'line'> | null>(null)
const selectedPatterns = ref<string[]>(['random_read', 'random_write', 'sequential_read', 'sequential_write'])

// Computed properties
const availablePatterns = computed(() => {
  const patterns = new Set<string>()
  props.data.forEach(blockData => {
    blockData.patterns.forEach(p => patterns.add(p.pattern))
  })
  return Array.from(patterns).sort()
})

const blockSizes = computed(() => {
  return [...new Set(props.data.map(d => d.blockSize))]
})

const maxIOPS = computed(() => {
  let max = 0
  props.data.forEach(blockData => {
    blockData.patterns.forEach(pattern => {
      if (selectedPatterns.value.includes(pattern.pattern) && pattern.iops && pattern.iops > max) {
        max = pattern.iops
      }
    })
  })
  return max
})

const avgIOPS = computed(() => {
  const values: number[] = []
  props.data.forEach(blockData => {
    blockData.patterns.forEach(pattern => {
      if (selectedPatterns.value.includes(pattern.pattern) && pattern.iops) {
        values.push(pattern.iops)
      }
    })
  })
  return values.length > 0 ? values.reduce((sum, val) => sum + val, 0) / values.length : 0
})

// Methods
const togglePattern = (pattern: string) => {
  const index = selectedPatterns.value.indexOf(pattern)
  if (index > -1) {
    selectedPatterns.value.splice(index, 1)
  } else {
    selectedPatterns.value.push(pattern)
  }
  updateChart()
}

const updateChart = () => {
  if (!chartInstance.value || !props.data.length) return

  // Filter data based on selected patterns
  const filteredData = props.data.map(blockData => ({
    ...blockData,
    patterns: blockData.patterns.filter(p => selectedPatterns.value.includes(p.pattern))
  }))

  const chartData = processIOPSComparisonData(filteredData, actualTheme.value)
  const chartOptions = createChartOptions()

  chartInstance.value.data = chartData
  chartInstance.value.options = chartOptions
  chartInstance.value.update()
}

const createChartOptions = () => {
  return {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      title: {
        display: true,
        text: 'IOPS Comparison by Block Size',
        color: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        font: {
          size: 16,
          weight: 'bold'
        }
      },
      legend: {
        display: true,
        position: 'top' as const,
        labels: {
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 12
          }
        }
      },
      tooltip: {
        enabled: true,
        backgroundColor: actualTheme.value === 'light' ? 'rgba(255, 255, 255, 0.9)' : 'rgba(31, 41, 55, 0.9)',
        titleColor: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        bodyColor: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
        borderColor: actualTheme.value === 'light' ? '#D1D5DB' : '#4B5563',
        borderWidth: 1,
        callbacks: {
          label: (context: { dataset: { label: string }; parsed: { y: number | null } }) => {
            const value = context.parsed.y
            return value !== null ? `${context.dataset.label}: ${value.toLocaleString()} IOPS` : `${context.dataset.label}: No data`
          }
        }
      }
    },
    scales: {
      x: {
        display: true,
        title: {
          display: true,
          text: 'Block Size',
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 14,
            weight: 'bold'
          }
        },
        ticks: {
          color: actualTheme.value === 'light' ? '#6B7280' : '#9CA3AF',
          font: {
            size: 12
          }
        },
        grid: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        }
      },
      y: {
        display: true,
        title: {
          display: true,
          text: 'IOPS',
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 14,
            weight: 'bold'
          }
        },
        ticks: {
          color: actualTheme.value === 'light' ? '#6B7280' : '#9CA3AF',
          font: {
            size: 12
          }
        },
        grid: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        }
      }
    }
  }
}

// Lifecycle
onMounted(() => {
  if (chartCanvas.value && props.data.length > 0) {
    const ctx = chartCanvas.value.getContext('2d')
    if (ctx) {
      const chartData = processIOPSComparisonData(props.data, actualTheme.value)
      const chartOptions = createChartOptions()

      chartInstance.value = new ChartJS(ctx, {
        type: 'line',
        data: chartData,
        options: chartOptions
      })
    }
  }
})

onUnmounted(() => {
  if (chartInstance.value) {
    chartInstance.value.destroy()
  }
})

// Watch for data changes
watch(() => props.data, updateChart, { deep: true })
watch(actualTheme, updateChart)
</script>

<style scoped>
.iops-comparison-chart {
  @apply w-full;
}

.chart-container {
  @apply w-full;
}

.stat-card {
  @apply bg-gray-50 dark:bg-gray-800 p-4 rounded-lg text-center;
}
</style>

// frontend/src/components/host/PerformanceGraphs/components/IOPSComparisonChart.tsx
/**
 * IOPS Comparison Chart Component
 *
 * Displays line chart comparing IOPS performance across different block sizes and patterns
 */

import React, { useMemo } from 'react';
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

import { useChartTheme } from '../hooks/useChartTheme';
import type { AggregatedData, ChartFilters, PatternType } from '../types';

// Register Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

interface IOPSComparisonChartProps {
  data: AggregatedData;
  filters?: ChartFilters;
  height?: number;
  className?: string;
}

/**
 * IOPS Comparison Chart Component
 */
export const IOPSComparisonChart: React.FC<IOPSComparisonChartProps> = ({
  data,
  height = 400,
  className = ''
}) => {
  const { theme, chartOptions } = useChartTheme('iops-comparison', data.series.length, data.blockSizes.length);

  // Process chart data
  const chartData = useMemo(() => {
    if (!data.series.length || !data.blockSizes.length) {
      return {
        labels: [],
        datasets: []
      };
    }

    const labels = data.blockSizes;
    const datasets = data.series.map((series, index) => {
      // Extract IOPS data for each block size
      const iopsData = labels.map(blockSize => {
        const dataPoint = series.data.find(point => point.blockSize === blockSize);
        return dataPoint?.iops || 0;
      });

      return {
        label: `${series.hostname} - ${series.driveModel}`,
        data: iopsData,
        backgroundColor: series.color || theme.colors.primary[index % theme.colors.primary.length],
        borderColor: series.color || theme.colors.primary[index % theme.colors.primary.length],
        borderWidth: 2,
        tension: 0.1,
        fill: false,
        pointRadius: 4,
        pointHoverRadius: 6,
        pointBorderWidth: 1,
        pointBorderColor: '#fff'
      };
    });

    return {
      labels,
      datasets: datasets.filter(dataset => dataset.data.some(value => value > 0))
    };
  }, [data, theme]);

  // Custom chart options for IOPS comparison
  const customOptions = useMemo(() => ({
    ...chartOptions,
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      ...chartOptions.plugins,
      title: {
        ...chartOptions.plugins.title,
        text: 'IOPS Performance Comparison'
      },
      tooltip: {
        ...chartOptions.plugins.tooltip,
        callbacks: {
          ...chartOptions.plugins.tooltip.callbacks,
          label: (context: any) => {
            const value = context.parsed.y;
            return `${context.dataset.label}: ${value.toLocaleString()} IOPS`;
          },
          afterLabel: (context: any) => {
            // Add pattern information if available
            const seriesIndex = context.datasetIndex;
            const blockSizeIndex = context.dataIndex;
            const series = data.series[seriesIndex];
            if (series && series.data[blockSizeIndex]) {
              const point = series.data[blockSizeIndex];
              return `Pattern: ${point.pattern.replace('_', ' ')}`;
            }
            return '';
          }
        }
      },
      legend: {
        ...chartOptions.plugins.legend,
        position: 'top',
        labels: {
          ...chartOptions.plugins.legend.labels,
          usePointStyle: true,
          padding: 20
        }
      }
    },
    scales: {
      ...chartOptions.scales,
      x: {
        ...chartOptions.scales.x,
        title: {
          ...chartOptions.scales.x.title,
          text: 'Block Size'
        }
      },
      y: {
        ...chartOptions.scales.y,
        title: {
          ...chartOptions.scales.y.title,
          text: 'IOPS (Operations/Second)'
        },
        beginAtZero: true,
        ticks: {
          ...chartOptions.scales.y.ticks,
          callback: function(value: any) {
            return typeof value === 'number' ? value.toLocaleString() : value;
          }
        }
      }
    },
    interaction: {
      mode: 'index',
      intersect: false
    },
    hover: {
      mode: 'index',
      intersect: false
    }
  }), [chartOptions, data.series]);

  // Show loading state if no data
  if (!data.series.length || !data.blockSizes.length) {
    return (
      <div
        className={`flex items-center justify-center bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 ${className}`}
        style={{ height }}
      >
        <div className="text-center text-gray-600 dark:text-gray-400">
          <div className="text-lg font-medium mb-2">No IOPS Data Available</div>
          <div className="text-sm">
            Select drives and test configurations to view IOPS comparison
          </div>
        </div>
      </div>
    );
  }

  // Show empty state if no valid datasets
  if (!chartData.datasets.length) {
    return (
      <div
        className={`flex items-center justify-center bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 ${className}`}
        style={{ height }}
      >
        <div className="text-center text-gray-600 dark:text-gray-400">
          <div className="text-lg font-medium mb-2">No Valid IOPS Data</div>
          <div className="text-sm">
            The selected data does not contain valid IOPS measurements
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 ${className}`}>
      <div style={{ height }}>
        <Line data={chartData} options={customOptions as any} />
      </div>

      {/* Chart legend with pattern indicators */}
      <div className="mt-4 flex flex-wrap gap-4 text-sm text-gray-600 dark:text-gray-400">
        {Array.from(new Set(data.series.flatMap(s => s.data.map(d => d.pattern)))).map((pattern: PatternType) => (
          <div key={pattern} className="flex items-center gap-2">
            <div
              className="w-3 h-3 rounded border"
              style={{
                backgroundColor: pattern.includes('read') ? theme.colors.primary[0] : theme.colors.primary[1] + '40',
                borderColor: pattern.includes('read') ? theme.colors.primary[0] : theme.colors.primary[1]
              }}
            />
            <span className="capitalize">{pattern.replace('_', ' ')}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default IOPSComparisonChart;
