// frontend-vue/src/components/PerformanceGraphs/components/LatencyAnalysisChart.vue
<template>
  <div class="latency-analysis-chart">
    <div class="chart-container" :style="{ height: height + 'px' }">
      <canvas ref="chartCanvas"></canvas>
    </div>

    <!-- Chart Stats -->
    <div class="chart-stats mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ (minLatency * 1000).toFixed(2) }}ns</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Min Latency</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ (avgLatency * 1000).toFixed(2) }}ns</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Avg Latency</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold">{{ latencyRange.toFixed(2) }}x</div>
        <div class="text-sm text-gray-600 dark:text-gray-400">Latency Range</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js'
import { useTheme } from '@/contexts/ThemeContext'
import { processLatencyAnalysisData } from '@/utils/chartProcessing'

// Register Chart.js components
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend)

interface Props {
  data: Array<{
    blockSize: string
    latency: number | null
    p95Latency: number | null
    p99Latency: number | null
  }>
  height?: number
}

const props = withDefaults(defineProps<Props>(), {
  height: 400
})

const { actualTheme } = useTheme()
const chartCanvas = ref<HTMLCanvasElement>()
const chartInstance = ref<ChartJS<'line'> | null>(null)

// Computed properties
const minLatency = computed(() => {
  const latencies = props.data.map(d => d.latency).filter(l => l !== null) as number[]
  return latencies.length > 0 ? Math.min(...latencies) : 0
})

const avgLatency = computed(() => {
  const latencies = props.data.map(d => d.latency).filter(l => l !== null) as number[]
  return latencies.length > 0 ? latencies.reduce((sum, l) => sum + l, 0) / latencies.length : 0
})

const latencyRange = computed(() => {
  const latencies = props.data.map(d => d.latency).filter(l => l !== null) as number[]
  if (latencies.length < 2) return 1
  const min = Math.min(...latencies)
  const max = Math.max(...latencies)
  return min > 0 ? max / min : 1
})

// Methods
const updateChart = () => {
  if (!chartInstance.value || !props.data.length) return

  const chartData = processLatencyAnalysisData(props.data, actualTheme.value)
  const chartOptions = createChartOptions()

  chartInstance.value.data = chartData
  chartInstance.value.options = chartOptions
  chartInstance.value.update()
}

const createChartOptions = () => {
  return {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      title: {
        display: true,
        text: 'Latency Analysis by Block Size',
        color: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        font: {
          size: 16,
          weight: 'bold'
        }
      },
      legend: {
        display: true,
        position: 'top' as const,
        labels: {
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 12
          }
        }
      },
      tooltip: {
        enabled: true,
        backgroundColor: actualTheme.value === 'light' ? 'rgba(255, 255, 255, 0.9)' : 'rgba(31, 41, 55, 0.9)',
        titleColor: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        bodyColor: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
        borderColor: actualTheme.value === 'light' ? '#D1D5DB' : '#4B5563',
        borderWidth: 1,
        callbacks: {
          label: (context: { dataset: { label: string }; parsed: { y: number | null } }) => {
            const value = context.parsed.y
            return value !== null ? `${context.dataset.label}: ${(value * 1000).toFixed(2)}ns` : `${context.dataset.label}: No data`
          }
        }
      }
    },
    scales: {
      x: {
        display: true,
        title: {
          display: true,
          text: 'Block Size',
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 14,
            weight: 'bold'
          }
        },
        ticks: {
          color: actualTheme.value === 'light' ? '#6B7280' : '#9CA3AF',
          font: {
            size: 12
          }
        },
        grid: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        }
      },
      y: {
        display: true,
        title: {
          display: true,
          text: 'Latency (ms)',
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 14,
            weight: 'bold'
          }
        },
        ticks: {
          color: actualTheme.value === 'light' ? '#6B7280' : '#9CA3AF',
          font: {
            size: 12
          },
          callback: (value: number | string) => `${value}ms`
        },
        grid: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        }
      }
    }
  }
}

// Lifecycle
onMounted(() => {
  if (chartCanvas.value && props.data.length > 0) {
    const ctx = chartCanvas.value.getContext('2d')
    if (ctx) {
      const chartData = processLatencyAnalysisData(props.data, actualTheme.value)
      const chartOptions = createChartOptions()

      chartInstance.value = new ChartJS(ctx, {
        type: 'line',
        data: chartData,
        options: chartOptions
      })
    }
  }
})

onUnmounted(() => {
  if (chartInstance.value) {
    chartInstance.value.destroy()
  }
})

// Watch for data changes
watch(() => props.data, updateChart, { deep: true })
watch(actualTheme, updateChart)
</script>

<style scoped>
.latency-analysis-chart {
  @apply w-full;
}

.stat-card {
  @apply bg-gray-50 dark:bg-gray-800 p-4 rounded-lg text-center;
}
</style>

// frontend/src/components/host/PerformanceGraphs/components/LatencyAnalysisChart.tsx
/**
 * Latency Analysis Chart Component
 *
 * Displays multi-axis line chart for latency metrics analysis with average and percentile latencies
 */

import React, { useMemo, useState } from 'react';
import { Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

import { useChartTheme } from '../hooks/useChartTheme';
import type { AggregatedData, ChartFilters } from '../types';

// Register Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

interface LatencyAnalysisChartProps {
  data: AggregatedData;
  filters?: ChartFilters;
  height?: number;
  className?: string;
}

type LatencyMetric = 'avg_latency' | 'p95_latency' | 'p99_latency';

/**
 * Latency Analysis Chart Component
 */
export const LatencyAnalysisChart: React.FC<LatencyAnalysisChartProps> = ({
  data,
  height = 400,
  className = ''
}) => {
  const { theme, chartOptions } = useChartTheme('latency-analysis', data.series.length, data.blockSizes.length);

  // Metric selection state
  const [selectedMetrics, setSelectedMetrics] = useState<LatencyMetric[]>(['avg_latency', 'p95_latency']);

  // Process chart data
  const chartData = useMemo(() => {
    if (!data.series.length || !data.blockSizes.length) {
      return {
        labels: [],
        datasets: []
      };
    }

    const labels = data.blockSizes;
    const datasets: any[] = [];

    data.series.forEach((series, seriesIndex) => {
      const baseColor = series.color || theme.colors.primary[seriesIndex % theme.colors.primary.length];

      // Average latency dataset (left axis)
      if (selectedMetrics.includes('avg_latency')) {
        const avgData = labels.map(blockSize => {
          const dataPoint = series.data.find(point => point.blockSize === blockSize);
          return dataPoint?.avgLatency || 0;
        });

        if (avgData.some(value => value > 0)) {
          datasets.push({
            label: `${series.hostname} - Avg Latency`,
            data: avgData,
            backgroundColor: baseColor,
            borderColor: baseColor,
            borderWidth: 2,
            tension: 0.1,
            fill: false,
            pointRadius: 4,
            pointHoverRadius: 6,
            yAxisID: 'y'
          });
        }
      }

      // P95 latency dataset (right axis)
      if (selectedMetrics.includes('p95_latency')) {
        const p95Data = labels.map(blockSize => {
          const dataPoint = series.data.find(point => point.blockSize === blockSize);
          return dataPoint?.p95Latency || 0;
        });

        if (p95Data.some(value => value > 0)) {
          datasets.push({
            label: `${series.hostname} - P95 Latency`,
            data: p95Data,
            backgroundColor: `${baseColor}80`,
            borderColor: baseColor,
            borderWidth: 1,
            borderDash: [5, 5],
            tension: 0.1,
            fill: false,
            pointRadius: 3,
            pointHoverRadius: 5,
            yAxisID: 'y1'
          });
        }
      }

      // P99 latency dataset (right axis)
      if (selectedMetrics.includes('p99_latency')) {
        const p99Data = labels.map(blockSize => {
          const dataPoint = series.data.find(point => point.blockSize === blockSize);
          return dataPoint?.p99Latency || 0;
        });

        if (p99Data.some(value => value > 0)) {
          datasets.push({
            label: `${series.hostname} - P99 Latency`,
            data: p99Data,
            backgroundColor: `${baseColor}60`,
            borderColor: baseColor,
            borderWidth: 1,
            borderDash: [2, 2],
            tension: 0.1,
            fill: false,
            pointRadius: 2,
            pointHoverRadius: 4,
            yAxisID: 'y1'
          });
        }
      }
    });

    return {
      labels,
      datasets
    };
  }, [data, theme, selectedMetrics]);

  // Custom chart options for dual-axis latency analysis
  const customOptions = useMemo(() => ({
    ...chartOptions,
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      ...chartOptions.plugins,
      title: {
        ...chartOptions.plugins.title,
        text: 'Latency Analysis - Average & Percentiles'
      },
      tooltip: {
        ...chartOptions.plugins.tooltip,
        callbacks: {
          ...chartOptions.plugins.tooltip.callbacks,
          label: (context: any) => {
            const value = context.parsed.y;
            return `${context.dataset.label}: ${value.toFixed(2)} ms`;
          }
        }
      },
      legend: {
        ...chartOptions.plugins.legend,
        position: 'top',
        labels: {
          ...chartOptions.plugins.legend.labels,
          usePointStyle: true,
          padding: 15,
          generateLabels: (chart: any) => {
            const original = ChartJS.defaults.plugins.legend.labels.generateLabels;
            const labels = original ? original(chart) : [];

            // Group labels by series and add visual indicators
            return labels.map((label) => ({
              ...label,
              pointStyle: label.text?.includes('P95') ? 'line' :
                         label.text?.includes('P99') ? 'dash' : 'circle'
            }));
          }
        }
      }
    },
    scales: {
      ...chartOptions.scales,
      x: {
        ...chartOptions.scales.x,
        title: {
          ...chartOptions.scales.x.title,
          text: 'Block Size'
        }
      },
      y: {
        ...chartOptions.scales.y,
        type: 'linear',
        display: true,
        position: 'left',
        title: {
          ...chartOptions.scales.y.title,
          text: 'Average Latency (ms)'
        },
        beginAtZero: true,
        ticks: {
          ...chartOptions.scales.y.ticks,
          callback: function(value: any) {
            return typeof value === 'number' ? `${value.toFixed(1)} ms` : value;
          }
        }
      },
      y1: {
        type: 'linear',
        display: true,
        position: 'right',
        title: {
          display: true,
          text: 'Percentile Latency (ms)',
          color: theme.theme.textColor
        },
        grid: {
          drawOnChartArea: false
        },
        ticks: {
          color: theme.theme.textColor,
          callback: function(value: any) {
            return typeof value === 'number' ? `${value.toFixed(1)} ms` : value;
          }
        }
      }
    },
    interaction: {
      mode: 'index',
      intersect: false
    }
  }), [chartOptions, theme]);

  // Toggle metric selection
  const toggleMetric = (metric: LatencyMetric) => {
    setSelectedMetrics(prev =>
      prev.includes(metric)
        ? prev.filter(m => m !== metric)
        : [...prev, metric]
    );
  };

  // Show loading state if no data
  if (!data.series.length || !data.blockSizes.length) {
    return (
      <div
        className={`flex items-center justify-center bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 ${className}`}
        style={{ height }}
      >
        <div className="text-center text-gray-600 dark:text-gray-400">
          <div className="text-lg font-medium mb-2">No Latency Data Available</div>
          <div className="text-sm">
            Select drives and test configurations to view latency analysis
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 ${className}`}>
      {/* Metric Selection Controls */}
      <div className="mb-4 flex flex-wrap gap-2">
        <span className="text-sm font-medium text-gray-900 dark:text-gray-100 mr-2">Metrics:</span>
        {(['avg_latency', 'p95_latency', 'p99_latency'] as LatencyMetric[]).map(metric => (
          <button
            key={metric}
            onClick={() => toggleMetric(metric)}
            className={`px-3 py-1 text-sm rounded border transition-colors ${
              selectedMetrics.includes(metric)
                ? 'bg-blue-600 text-white border-blue-600'
                : 'bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-600'
            }`}
          >
            {metric === 'avg_latency' ? 'Average' :
             metric === 'p95_latency' ? 'P95' : 'P99'}
          </button>
        ))}
      </div>

      {/* Chart */}
      <div style={{ height }}>
        {chartData.datasets.length > 0 ? (
          <Line data={chartData} options={customOptions as any} />
        ) : (
          <div className="flex items-center justify-center h-full text-center text-gray-600 dark:text-gray-400">
            <div>
              <div className="text-lg font-medium mb-2">No Data for Selected Metrics</div>
              <div className="text-sm">
                Select different metrics or check data availability
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Chart Info */}
      <div className="mt-4 flex flex-wrap gap-4 text-sm text-gray-600 dark:text-gray-400">
        <div className="flex items-center gap-2">
          <div className="w-3 h-0.5 bg-current" />
          <span>Average (Left Axis)</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-0.5 border-t-2 border-dashed border-current" />
          <span>P95 (Right Axis)</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-0.5 border-t border-dotted border-current" />
          <span>P99 (Right Axis)</span>
        </div>
      </div>
    </div>
  );
};

export default LatencyAnalysisChart;
