// frontend/src/components/host/DriveRadarChart.tsx
import React from 'react';
import {
    Chart as ChartJS,
    RadialLinearScale,
    PointElement,
    LineElement,
    Filler,
    Tooltip,
    Legend,
} from 'chart.js';
import { Radar } from 'react-chartjs-2';
import type { DriveAnalysis } from '../../services/api/hostAnalysis';
import { useThemeColors } from '../../hooks/useThemeColors';
import { createChartJsColors } from '../../utils/colorMapping';

ChartJS.register(
    RadialLinearScale,
    PointElement,
    LineElement,
    Filler,
    Tooltip,
    Legend
);

interface DriveRadarChartProps {
    drives: DriveAnalysis[];
}

const DriveRadarChart: React.FC<DriveRadarChartProps> = ({ drives }) => {
    const themeColors = useThemeColors();

    // Calculate performance scores for each drive
    const driveScores = drives.map(drive => {
        const validConfigs = drive.configurations.filter(c => 
            c.iops !== null && c.avg_latency !== null && c.bandwidth !== null
        );

        if (validConfigs.length === 0) {
            return {
                drive_model: drive.drive_model,
                maxIOPS: 0,
                avgIOPS: 0,
                minLatency: 0,
                avgLatency: 0,
                maxBandwidth: 0,
                avgBandwidth: 0,
                consistency: 0
            };
        }

        const iopsValues = validConfigs.map(c => c.iops!);
        const latencyValues = validConfigs.map(c => c.avg_latency!);
        const bandwidthValues = validConfigs.map(c => c.bandwidth!);

        // Calculate consistency (lower coefficient of variation = higher consistency)
        const calculateCV = (values: number[]) => {
            const mean = values.reduce((sum, val) => sum + val, 0) / values.length;
            const variance = values.reduce((sum, val) => sum + Math.pow(val - mean, 2), 0) / values.length;
            const stdDev = Math.sqrt(variance);
            return mean > 0 ? stdDev / mean : 0;
        };

        const iopsCV = calculateCV(iopsValues);
        const latencyCV = calculateCV(latencyValues);
        const bandwidthCV = calculateCV(bandwidthValues);
        const overallConsistency = 1 - ((iopsCV + latencyCV + bandwidthCV) / 3);

        return {
            drive_model: drive.drive_model,
            maxIOPS: Math.max(...iopsValues),
            avgIOPS: iopsValues.reduce((sum, val) => sum + val, 0) / iopsValues.length,
            minLatency: Math.min(...latencyValues),
            avgLatency: latencyValues.reduce((sum, val) => sum + val, 0) / latencyValues.length,
            maxBandwidth: Math.max(...bandwidthValues),
            avgBandwidth: bandwidthValues.reduce((sum, val) => sum + val, 0) / bandwidthValues.length,
            consistency: Math.max(0, Math.min(1, overallConsistency))
        };
    });

    // Normalize scores to 0-100 scale
    const allMaxIOPS = driveScores.map(d => d.maxIOPS);
    const allMinLatency = driveScores.map(d => d.minLatency).filter(l => l > 0);
    const allMaxBandwidth = driveScores.map(d => d.maxBandwidth);

    const maxIOPSOverall = Math.max(...allMaxIOPS);
    const minLatencyOverall = Math.min(...allMinLatency);
    const maxLatencyOverall = Math.max(...allMinLatency);
    const maxBandwidthOverall = Math.max(...allMaxBandwidth);

    const normalizedData = driveScores.map(drive => ({
        drive_model: drive.drive_model,
        maxIOPS: maxIOPSOverall > 0 ? (drive.maxIOPS / maxIOPSOverall) * 100 : 0,
        avgIOPS: maxIOPSOverall > 0 ? (drive.avgIOPS / maxIOPSOverall) * 100 : 0,
        latencyScore: allMinLatency.length > 0 ? 
            100 - ((drive.minLatency - minLatencyOverall) / (maxLatencyOverall - minLatencyOverall)) * 100 : 0,
        avgLatencyScore: allMinLatency.length > 0 ? 
            100 - ((drive.avgLatency - minLatencyOverall) / (maxLatencyOverall - minLatencyOverall)) * 100 : 0,
        maxBandwidth: maxBandwidthOverall > 0 ? (drive.maxBandwidth / maxBandwidthOverall) * 100 : 0,
        avgBandwidth: maxBandwidthOverall > 0 ? (drive.avgBandwidth / maxBandwidthOverall) * 100 : 0,
        consistency: drive.consistency * 100
    }));

    const radarLabels = [
        'Peak IOPS',
        'Avg IOPS', 
        'Low Latency',
        'Avg Latency',
        'Peak Bandwidth',
        'Avg Bandwidth',
        'Consistency'
    ];

    // Generate unique colors based on hostname and drive model
    const chartColors = createChartJsColors(
        drives.map(drive => ({
            hostname: drive.hostname,
            driveModel: drive.drive_model,
            label: drive.drive_model
        }))
    );

    const datasets = normalizedData.map((drive, index) => {
        const colors = chartColors[index];
        return {
            label: drive.drive_model,
            data: [
                drive.maxIOPS,
                drive.avgIOPS,
                drive.latencyScore,
                drive.avgLatencyScore,
                drive.maxBandwidth,
                drive.avgBandwidth,
                drive.consistency
            ],
            backgroundColor: colors.backgroundColor,
            borderColor: colors.borderColor,
            borderWidth: 2,
            pointBackgroundColor: colors.pointBackgroundColor,
            pointBorderColor: '#fff',
            pointHoverBackgroundColor: '#fff',
            pointHoverBorderColor: colors.borderColor,
        };
    });

    const chartData = {
        labels: radarLabels,
        datasets
    };

    const options = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                position: 'top' as const,
                labels: {
                    color: themeColors.chart.text,
                    usePointStyle: true,
                    padding: 20,
                },
            },
            tooltip: {
                backgroundColor: themeColors.chart.tooltipBg,
                titleColor: themeColors.text.primary,
                bodyColor: themeColors.text.secondary,
                borderColor: themeColors.chart.tooltipBorder,
                borderWidth: 1,
                cornerRadius: 8,
                padding: 12,
                callbacks: {
                    title: (context: any) => {
                        const driveLabel = context[0].dataset.label || '';
                        const metricLabel = context[0].label || '';
                        return `${driveLabel} - ${metricLabel}`;
                    },
                    label: (context: any) => {
                        const driveIndex = context.datasetIndex;
                        const drive = driveScores[driveIndex];
                        const metricIndex = context.dataIndex;
                        const normalizedScore = context.parsed.r.toFixed(1);
                        
                        const metricDetails = [
                            `Score: ${normalizedScore}%`,
                            '',
                            `Drive Type: ${drives[driveIndex].drive_type}`,
                            `Protocol: ${drives[driveIndex].protocol}`,
                            '',
                            `Raw Performance Data:`
                        ];
                        
                        switch (metricIndex) {
                            case 0: // Peak IOPS
                                metricDetails.push(`Peak IOPS: ${drive.maxIOPS.toFixed(0)}`);
                                break;
                            case 1: // Avg IOPS
                                metricDetails.push(`Average IOPS: ${drive.avgIOPS.toFixed(0)}`);
                                break;
                            case 2: // Low Latency
                                metricDetails.push(`Lowest Latency: ${drive.minLatency.toFixed(2)}ms`);
                                break;
                            case 3: // Avg Latency
                                metricDetails.push(`Average Latency: ${drive.avgLatency.toFixed(2)}ms`);
                                break;
                            case 4: // Peak Bandwidth
                                metricDetails.push(`Peak Bandwidth: ${drive.maxBandwidth.toFixed(1)} MB/s`);
                                break;
                            case 5: // Avg Bandwidth
                                metricDetails.push(`Average Bandwidth: ${drive.avgBandwidth.toFixed(1)} MB/s`);
                                break;
                            case 6: // Consistency
                                metricDetails.push(`Consistency Score: ${(drive.consistency * 100).toFixed(1)}%`);
                                metricDetails.push(`(Lower variation = higher consistency)`);
                                break;
                        }
                        
                        const validConfigs = drives[driveIndex].configurations.filter(c => 
                            c.iops !== null && c.avg_latency !== null && c.bandwidth !== null
                        );
                        metricDetails.push('');
                        metricDetails.push(`Test Configurations: ${validConfigs.length}`);
                        
                        return metricDetails;
                    }
                }
            },
        },
        scales: {
            r: {
                beginAtZero: true,
                max: 100,
                ticks: {
                    color: themeColors.chart.text,
                    stepSize: 20,
                    callback: function(value: any) {
                        return value + '%';
                    }
                },
                grid: {
                    color: themeColors.chart.grid,
                },
                angleLines: {
                    color: themeColors.chart.grid,
                },
                pointLabels: {
                    color: themeColors.chart.text,
                    font: {
                        size: 12,
                    },
                }
            }
        },
        interaction: {
            intersect: false,
        },
        animation: {
            duration: 1000,
            easing: 'easeOutQuart' as const,
        },
    };

    return (
        <div className="w-full h-[500px]">
            <div className="mb-4">
                <h4 className="text-lg font-semibold theme-text-primary mb-2">
                    Drive Performance Comparison
                </h4>
                <p className="text-sm theme-text-secondary">
                    Multi-dimensional performance analysis (normalized to 0-100% scale)
                </p>
            </div>
            <div className="h-[400px]">
                <Radar data={chartData} options={options} />
            </div>
        </div>
    );
};

export default DriveRadarChart;

// frontend-vue/src/components/DriveRadarChart.vue
<template>
  <div class="drive-radar-chart">
    <!-- Header -->
    <div class="mb-6">
      <h4 class="text-xl font-bold theme-text-primary mb-2">
        Drive Performance Radar
      </h4>
      <p class="text-sm theme-text-secondary mb-4">
        Multi-dimensional comparison of drive performance across key metrics.
      </p>
    </div>

    <!-- Chart Container -->
    <div class="chart-container bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-6">
      <div class="chart-wrapper" :style="{ height: height + 'px' }">
        <canvas ref="chartCanvas"></canvas>
      </div>
    </div>

    <!-- Drive Selection -->
    <div class="drive-selection mt-6">
      <label class="block text-sm font-medium mb-2 theme-text-primary">Compare Drives</label>
      <div class="flex flex-wrap gap-2">
        <button
          v-for="drive in availableDrives"
          :key="drive.hostname + '-' + drive.driveModel"
          @click="toggleDrive(drive)"
          :class="[
            'px-3 py-1 rounded-full text-sm transition-colors',
            selectedDrives.some(d => d.hostname === drive.hostname && d.driveModel === drive.driveModel)
              ? 'bg-blue-500 text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600'
          ]"
        >
          {{ drive.hostname }} - {{ drive.driveModel }}
        </button>
      </div>
    </div>

    <!-- Metric Selection -->
    <div class="metric-selection mt-4">
      <label class="block text-sm font-medium mb-2 theme-text-primary">Metrics to Display</label>
      <div class="flex flex-wrap gap-2">
        <label
          v-for="metric in availableMetrics"
          :key="metric.key"
          class="flex items-center"
        >
          <input
            v-model="selectedMetrics"
            :value="metric.key"
            type="checkbox"
            class="mr-2"
          >
          <span class="text-sm theme-text-primary">{{ metric.label }}</span>
        </label>
      </div>
    </div>

    <!-- Statistics -->
    <div class="stats mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
      <div class="stat-card">
        <div class="text-lg font-semibold theme-text-primary">{{ selectedDrives.length }}</div>
        <div class="text-xs theme-text-secondary">Selected Drives</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold theme-text-primary">{{ selectedMetrics.length }}</div>
        <div class="text-xs theme-text-secondary">Active Metrics</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold theme-text-primary">{{ maxValue.toFixed(1) }}</div>
        <div class="text-xs theme-text-secondary">Scale Max</div>
      </div>
      <div class="stat-card">
        <div class="text-lg font-semibold theme-text-primary">{{ totalConfigurations }}</div>
        <div class="text-xs theme-text-secondary">Total Configs</div>
      </div>
    </div>

    <!-- Instructions -->
    <div class="instructions mt-4 p-4 bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg">
      <h5 class="text-sm font-semibold text-blue-800 dark:text-blue-200 mb-2">How to Read</h5>
      <ul class="text-xs text-blue-700 dark:text-blue-300 space-y-1">
        <li>• Each drive is represented by a colored shape</li>
        <li>• Distance from center indicates performance level</li>
        <li>• Regular polygons suggest balanced performance</li>
        <li>• Irregular shapes highlight performance strengths/weaknesses</li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { Chart as ChartJS, RadialLinearScale, PointElement, LineElement, Filler, Title, Tooltip, Legend } from 'chart.js'
import { Radar } from 'chart.js'
import { useTheme } from '@/contexts/ThemeContext'
import { generateColorPalette } from '@/utils/chartProcessing'
import type { DriveAnalysis } from '@/types/performance'

// Register Chart.js components
ChartJS.register(RadialLinearScale, PointElement, LineElement, Filler, Title, Tooltip, Legend)

interface Props {
  drives: DriveAnalysis[]
  height?: number
}

const props = withDefaults(defineProps<Props>(), {
  height: 400
})

const { actualTheme } = useTheme()
const chartCanvas = ref<HTMLCanvasElement>()
const chartInstance = ref<any>(null)

// State
const selectedDrives = ref<DriveAnalysis[]>([])
const selectedMetrics = ref<string[]>(['iops', 'avg_latency', 'bandwidth'])

// Computed
const availableDrives = computed(() => {
  return props.drives.slice(0, 8) // Limit to 8 drives for readability
})

const availableMetrics = computed(() => [
  { key: 'iops', label: 'IOPS' },
  { key: 'avg_latency', label: 'Avg Latency' },
  { key: 'bandwidth', label: 'Bandwidth' },
  { key: 'p95_latency', label: '95th % Latency' },
  { key: 'p99_latency', label: '99th % Latency' }
])

const totalConfigurations = computed(() => {
  return selectedDrives.value.reduce((sum, drive) => sum + drive.configurations.length, 0)
})

const maxValue = computed(() => {
  if (selectedDrives.value.length === 0 || selectedMetrics.value.length === 0) return 100

  let max = 0
  selectedDrives.value.forEach(drive => {
    selectedMetrics.value.forEach(metric => {
      const avgValue = getDriveMetricAverage(drive, metric)
      if (avgValue > max) max = avgValue
    })
  })
  return max
})

// Methods
const toggleDrive = (drive: DriveAnalysis) => {
  const existingIndex = selectedDrives.value.findIndex(
    d => d.hostname === drive.hostname && d.driveModel === drive.driveModel
  )

  if (existingIndex > -1) {
    selectedDrives.value.splice(existingIndex, 1)
  } else if (selectedDrives.value.length < 6) { // Limit to 6 for readability
    selectedDrives.value.push(drive)
  }

  updateChart()
}

const getDriveMetricAverage = (drive: DriveAnalysis, metric: string): number => {
  if (drive.configurations.length === 0) return 0

  const values = drive.configurations.map(config => {
    switch (metric) {
      case 'iops': return config.iops || 0
      case 'avg_latency': return config.avg_latency || 0
      case 'bandwidth': return config.bandwidth || 0
      case 'p95_latency': return config.p95_latency || 0
      case 'p99_latency': return config.p99_latency || 0
      default: return 0
    }
  }).filter(v => v > 0)

  return values.length > 0 ? values.reduce((sum, v) => sum + v, 0) / values.length : 0
}

const updateChart = () => {
  if (!chartInstance.value) return

  const chartData = createChartData()
  const chartOptions = createChartOptions()

  chartInstance.value.data = chartData
  chartInstance.value.options = chartOptions
  chartInstance.value.update()
}

const createChartData = () => {
  const colors = generateColorPalette(selectedDrives.value.length, actualTheme.value)

  const datasets = selectedDrives.value.map((drive, index) => {
    const data = selectedMetrics.value.map(metric => {
      const avgValue = getDriveMetricAverage(drive, metric)

      // Normalize latency metrics (lower is better, so invert)
      if (metric.includes('latency')) {
        return maxValue.value > 0 ? (maxValue.value - avgValue) / maxValue.value * 100 : 0
      }

      // For other metrics, higher is better
      return maxValue.value > 0 ? (avgValue / maxValue.value) * 100 : 0
    })

    return {
      label: `${drive.hostname} - ${drive.driveModel}`,
      data,
      borderColor: colors[index],
      backgroundColor: colors[index] + '20',
      borderWidth: 2,
      pointRadius: 4,
      pointHoverRadius: 6,
    }
  })

  return {
    labels: selectedMetrics.value.map(metric => {
      const metricInfo = availableMetrics.value.find(m => m.key === metric)
      return metricInfo?.label || metric
    }),
    datasets
  }
}

const createChartOptions = () => {
  return {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      title: {
        display: true,
        text: 'Drive Performance Comparison',
        color: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        font: {
          size: 16,
          weight: 'bold'
        }
      },
      legend: {
        display: selectedDrives.value.length > 1,
        position: 'top' as const,
        labels: {
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 12
          }
        }
      },
      tooltip: {
        enabled: true,
        backgroundColor: actualTheme.value === 'light' ? 'rgba(255, 255, 255, 0.9)' : 'rgba(31, 41, 55, 0.9)',
        titleColor: actualTheme.value === 'light' ? '#1F2937' : '#F9FAFB',
        bodyColor: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
        borderColor: actualTheme.value === 'light' ? '#D1D5DB' : '#4B5563',
        borderWidth: 1,
        callbacks: {
          label: (context: any) => {
            const originalValue = getOriginalValue(context)
            return `${context.dataset.label}: ${originalValue}`
          }
        }
      }
    },
    scales: {
      r: {
        beginAtZero: true,
        max: 100,
        ticks: {
          color: actualTheme.value === 'light' ? '#6B7280' : '#9CA3AF',
          font: {
            size: 11
          },
          callback: (value: any) => `${value}%`
        },
        grid: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        },
        angleLines: {
          color: actualTheme.value === 'light' ? '#E5E7EB' : '#374151'
        },
        pointLabels: {
          color: actualTheme.value === 'light' ? '#374151' : '#D1D5DB',
          font: {
            size: 12,
            weight: 'bold'
          }
        }
      }
    }
  }
}

const getOriginalValue = (context: any) => {
  const datasetIndex = context.datasetIndex
  const dataIndex = context.dataIndex
  const drive = selectedDrives.value[datasetIndex]
  const metric = selectedMetrics.value[dataIndex]

  if (!drive) return 'N/A'

  const avgValue = getDriveMetricAverage(drive, metric)

  if (metric.includes('latency')) {
    return `${avgValue.toFixed(3)}ms`
  } else if (metric === 'iops') {
    return avgValue.toLocaleString() + ' IOPS'
  } else if (metric === 'bandwidth') {
    return avgValue.toFixed(1) + ' MB/s'
  }

  return avgValue.toFixed(2)
}

// Lifecycle
onMounted(() => {
  if (chartCanvas.value) {
    const ctx = chartCanvas.value.getContext('2d')
    if (ctx) {
      const chartData = createChartData()
      const chartOptions = createChartOptions()

      chartInstance.value = new ChartJS(ctx, {
        type: 'radar',
        data: chartData,
        options: chartOptions
      })
    }
  }

  // Auto-select first few drives
  if (props.drives.length > 0 && selectedDrives.value.length === 0) {
    selectedDrives.value = props.drives.slice(0, Math.min(3, props.drives.length))
    updateChart()
  }
})

onUnmounted(() => {
  if (chartInstance.value) {
    chartInstance.value.destroy()
  }
})

// Watchers
watch(() => props.drives, () => {
  // Reset selection when drives change
  selectedDrives.value = props.drives.slice(0, Math.min(3, props.drives.length))
  updateChart()
})

watch(selectedMetrics, updateChart)
watch(actualTheme, updateChart)
</script>

<style scoped>
.drive-radar-chart {
  @apply w-full;
}

.theme-text-primary {
  @apply text-gray-900 dark:text-white;
}

.theme-text-secondary {
  @apply text-gray-600 dark:text-gray-300;
}

.stat-card {
  @apply bg-gray-50 dark:bg-gray-800 p-4 rounded-lg text-center;
}

.chart-wrapper {
  @apply w-full;
}
</style>
