// frontend-vue/src/pages/Upload.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <header class="bg-white border-b border-gray-200 px-6 py-4">
      <div class="flex items-center justify-between max-w-4xl mx-auto">
        <h1 class="text-2xl font-bold text-gray-900">Upload FIO Test Data</h1>
        <router-link to="/" class="btn-secondary">
          Back to Comparison
        </router-link>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-4xl mx-auto p-6">
      <div class="card">
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- File Upload -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              FIO JSON Output File *
            </label>
            <input
              type="file"
              accept=".json"
              @change="handleFileChange"
              required
              class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"
            />
            <p class="mt-1 text-sm text-gray-500">
              Upload the JSON output file from your FIO benchmark test
            </p>
          </div>

          <!-- Hostname -->
          <div>
            <label for="hostname" class="block text-sm font-medium text-gray-700 mb-1">
              Hostname *
            </label>
            <input
              id="hostname"
              v-model="formData.hostname"
              type="text"
              required
              class="input-field"
              placeholder="e.g., server-01"
            />
          </div>

          <!-- Drive Model -->
          <div>
            <label for="drive_model" class="block text-sm font-medium text-gray-700 mb-1">
              Drive Model *
            </label>
            <input
              id="drive_model"
              v-model="formData.drive_model"
              type="text"
              required
              class="input-field"
              placeholder="e.g., Samsung SSD 980 PRO"
            />
          </div>

          <!-- Drive Type -->
          <div>
            <label for="drive_type" class="block text-sm font-medium text-gray-700 mb-1">
              Drive Type *
            </label>
            <select
              id="drive_type"
              v-model="formData.drive_type"
              required
              class="input-field"
            >
              <option value="">Select drive type...</option>
              <option value="NVMe">NVMe</option>
              <option value="SATA">SATA</option>
              <option value="SAS">SAS</option>
            </select>
          </div>

          <!-- Protocol -->
          <div>
            <label for="protocol" class="block text-sm font-medium text-gray-700 mb-1">
              Protocol *
            </label>
            <select
              id="protocol"
              v-model="formData.protocol"
              required
              class="input-field"
            >
              <option value="">Select protocol...</option>
              <option value="Local">Local</option>
              <option value="iSCSI">iSCSI</option>
              <option value="NFS">NFS</option>
            </select>
          </div>

          <!-- Description -->
          <div>
            <label for="description" class="block text-sm font-medium text-gray-700 mb-1">
              Description
            </label>
            <textarea
              id="description"
              v-model="formData.description"
              rows="3"
              class="input-field"
              placeholder="Optional description of the test..."
            ></textarea>
          </div>

          <!-- Test Date -->
          <div>
            <label for="date" class="block text-sm font-medium text-gray-700 mb-1">
              Test Date (optional)
            </label>
            <input
              id="date"
              v-model="formData.date"
              type="datetime-local"
              class="input-field"
            />
            <p class="mt-1 text-sm text-gray-500">
              Leave blank to use current date and time
            </p>
          </div>

          <!-- Success Message -->
          <div v-if="successMessage" class="p-4 bg-green-50 border border-green-200 rounded-lg">
            <p class="text-green-800 font-semibold">{{ successMessage }}</p>
          </div>

          <!-- Error Message -->
          <div v-if="errorMessage" class="p-4 bg-red-50 border border-red-200 rounded-lg">
            <p class="text-red-800 font-semibold">{{ errorMessage }}</p>
          </div>

          <!-- Submit Button -->
          <div class="flex gap-4">
            <button
              type="submit"
              :disabled="loading || !selectedFile"
              class="btn-primary"
            >
              {{ loading ? 'Uploading...' : 'Upload Test Data' }}
            </button>
            <button
              type="button"
              @click="resetForm"
              :disabled="loading"
              class="btn-secondary"
            >
              Reset Form
            </button>
          </div>
        </form>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useApi } from '../composables/useApi'

const api = useApi()

const selectedFile = ref<File | null>(null)
const loading = ref(false)
const successMessage = ref('')
const errorMessage = ref('')

const formData = ref({
  hostname: '',
  drive_model: '',
  drive_type: '',
  protocol: '',
  description: '',
  date: ''
})

function handleFileChange(event: Event) {
  const target = event.target as HTMLInputElement
  if (target.files && target.files.length > 0) {
    selectedFile.value = target.files[0]
  }
}

async function handleSubmit() {
  if (!selectedFile.value) {
    errorMessage.value = 'Please select a file'
    return
  }

  loading.value = true
  successMessage.value = ''
  errorMessage.value = ''

  try {
    const formDataToSend = new FormData()
    formDataToSend.append('file', selectedFile.value)
    formDataToSend.append('hostname', formData.value.hostname)
    formDataToSend.append('drive_model', formData.value.drive_model)
    formDataToSend.append('drive_type', formData.value.drive_type)
    formDataToSend.append('protocol', formData.value.protocol)

    if (formData.value.description) {
      formDataToSend.append('description', formData.value.description)
    }

    if (formData.value.date) {
      formDataToSend.append('date', formData.value.date)
    }

    const result = await api.uploadTestData(formDataToSend)
    successMessage.value = `Success! ${result.message} (Test Run ID: ${result.test_run_id})`

    // Reset form after successful upload
    setTimeout(() => {
      resetForm()
      successMessage.value = ''
    }, 3000)
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'Upload failed'
    console.error('Upload error:', error)
  } finally {
    loading.value = false
  }
}

function resetForm() {
  selectedFile.value = null
  formData.value = {
    hostname: '',
    drive_model: '',
    drive_type: '',
    protocol: '',
    description: '',
    date: ''
  }
  successMessage.value = ''
  errorMessage.value = ''

  // Reset file input
  const fileInput = document.querySelector('input[type="file"]') as HTMLInputElement
  if (fileInput) {
    fileInput.value = ''
  }
}
</script>

// frontend/src/pages/Upload.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Upload as UploadIcon, Check, AlertCircle, ArrowLeft, FileText } from 'lucide-react';

export default function Upload() {
  const navigate = useNavigate();
  const [file, setFile] = useState<File | null>(null);
  const [driveModel, setDriveModel] = useState('');
  const [driveType, setDriveType] = useState('');
  const [customDriveType, setCustomDriveType] = useState('');
  const [showCustomType, setShowCustomType] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setMessage(null);
    }
  };

  const handleDriveTypeChange = (value: string) => {
    if (value === 'custom') {
      setShowCustomType(true);
      setDriveType('');
    } else {
      setShowCustomType(false);
      setDriveType(value);
      setCustomDriveType('');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!file) {
      setMessage({ type: 'error', text: 'Please select a FIO JSON file' });
      return;
    }

    setUploading(true);
    
    const finalDriveType = showCustomType ? customDriveType : driveType;
    
    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('drive_model', driveModel || 'Unknown');
      formData.append('drive_type', finalDriveType || 'Unknown');

      const response = await fetch('http://localhost:8000/api/import', {
        method: 'POST',
        body: formData,
      });

      const result = await response.json();

      if (response.ok) {
        setMessage({ type: 'success', text: 'FIO results imported successfully!' });
        setFile(null);
        setDriveModel('');
        setDriveType('');
        setCustomDriveType('');
        setShowCustomType(false);
        
        // Reset file input
        const fileInput = document.getElementById('file-input') as HTMLInputElement;
        if (fileInput) fileInput.value = '';

        // Navigate back to home after 2 seconds
        setTimeout(() => {
          navigate('/');
        }, 2000);
      } else {
        setMessage({ type: 'error', text: result.error || 'Import failed' });
      }
    } catch (error) {
      setMessage({ type: 'error', text: 'Network error occurred' });
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <button
              onClick={() => navigate('/')}
              className="flex items-center text-gray-600 hover:text-gray-900 transition-colors"
            >
              <ArrowLeft className="h-5 w-5 mr-2" />
              Back to Dashboard
            </button>
            <div className="flex items-center">
              <UploadIcon className="h-8 w-8 text-blue-600 mr-3" />
              <h1 className="text-2xl font-bold text-gray-900">Upload FIO Results</h1>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-lg p-8">
          {/* Instructions */}
          <div className="mb-8">
            <div className="flex items-center mb-4">
              <FileText className="h-6 w-6 text-blue-600 mr-3" />
              <h2 className="text-xl font-semibold text-gray-900">Import Benchmark Data</h2>
            </div>
            <p className="text-gray-600 mb-4">
              Upload FIO JSON output files to analyze storage performance metrics. The system will automatically 
              extract IOPS, latency, throughput, and detailed percentile data from your benchmark results.
            </p>
            
            {/* FIO Command Examples */}
            <div className="bg-gray-50 rounded-lg p-4 mb-6">
              <h3 className="font-medium text-gray-900 mb-2">Generate FIO JSON files with these commands:</h3>
              <div className="space-y-2 text-sm font-mono text-gray-700">
                <div className="bg-white p-2 rounded border">
                  <div className="text-gray-500 text-xs mb-1"># Sequential read test</div>
                  <div>fio --name=seqread --rw=read --bs=64k --iodepth=16 --runtime=60 --time_based --output-format=json --output=results.json</div>
                </div>
                <div className="bg-white p-2 rounded border">
                  <div className="text-gray-500 text-xs mb-1"># Random mixed workload</div>
                  <div>fio --name=randtest --rw=randrw --rwmixread=70 --bs=4k --iodepth=32 --runtime=120 --time_based --output-format=json --output=results.json</div>
                </div>
              </div>
            </div>
          </div>

          {/* Upload Form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* File Upload */}
            <div>
              <label htmlFor="file-input" className="block text-sm font-medium text-gray-700 mb-2">
                FIO JSON Results File *
              </label>
              <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-lg hover:border-gray-400 transition-colors">
                <div className="space-y-1 text-center">
                  <UploadIcon className="mx-auto h-12 w-12 text-gray-400" />
                  <div className="flex text-sm text-gray-600">
                    <label
                      htmlFor="file-input"
                      className="relative cursor-pointer bg-white rounded-md font-medium text-blue-600 hover:text-blue-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-blue-500"
                    >
                      <span>Upload a file</span>
                      <input
                        id="file-input"
                        name="file-upload"
                        type="file"
                        accept=".json"
                        className="sr-only"
                        onChange={handleFileChange}
                      />
                    </label>
                    <p className="pl-1">or drag and drop</p>
                  </div>
                  <p className="text-xs text-gray-500">JSON files only</p>
                </div>
              </div>
              {file && (
                <div className="mt-2 text-sm text-gray-600">
                  Selected: <span className="font-medium">{file.name}</span>
                </div>
              )}
            </div>

            {/* Drive Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label htmlFor="drive-model" className="block text-sm font-medium text-gray-700 mb-2">
                  Drive Model
                </label>
                <input
                  id="drive-model"
                  type="text"
                  value={driveModel}
                  onChange={(e) => setDriveModel(e.target.value)}
                  placeholder="e.g., Samsung 980 PRO"
                  className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                />
                <p className="mt-1 text-xs text-gray-500">Optional: Specify the storage device model</p>
              </div>

              <div>
                <label htmlFor="drive-type" className="block text-sm font-medium text-gray-700 mb-2">
                  Drive Type
                </label>
                {!showCustomType ? (
                  <select
                    id="drive-type"
                    value={driveType}
                    onChange={(e) => handleDriveTypeChange(e.target.value)}
                    className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                  >
                    <option value="">Select type</option>
                    <option value="NVMe SSD">NVMe SSD</option>
                    <option value="SATA SSD">SATA SSD</option>
                    <option value="HDD">HDD</option>
                    <option value="Optane">Optane</option>
                    <option value="eUFS">eUFS</option>
                    <option value="eMMC">eMMC</option>
                    <option value="SD Card">SD Card</option>
                    <option value="custom">+ Add Custom Type</option>
                  </select>
                ) : (
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={customDriveType}
                      onChange={(e) => setCustomDriveType(e.target.value)}
                      placeholder="Enter custom drive type"
                      className="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm"
                    />
                    <button
                      type="button"
                      onClick={() => {
                        setShowCustomType(false);
                        setCustomDriveType('');
                        setDriveType('');
                      }}
                      className="px-3 py-2 text-sm text-gray-600 bg-gray-100 rounded-md hover:bg-gray-200"
                    >
                      Cancel
                    </button>
                  </div>
                )}
                <p className="mt-1 text-xs text-gray-500">Optional: Categorize the storage device</p>
              </div>
            </div>

            {/* Submit Button */}
            <div className="flex items-center justify-between pt-6">
              <button
                type="submit"
                disabled={!file || uploading}
                className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
              >
                {uploading ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-3"></div>
                    Importing Results...
                  </>
                ) : (
                  <>
                    <UploadIcon className="h-5 w-5 mr-3" />
                    Import FIO Results
                  </>
                )}
              </button>

              {message && (
                <div className={`flex items-center ${message.type === 'success' ? 'text-green-600' : 'text-red-600'}`}>
                  {message.type === 'success' ? (
                    <Check className="h-5 w-5 mr-2" />
                  ) : (
                    <AlertCircle className="h-5 w-5 mr-2" />
                  )}
                  <span className="font-medium">{message.text}</span>
                </div>
              )}
            </div>
          </form>

          {/* Success Message */}
          {message?.type === 'success' && (
            <div className="mt-6 bg-green-50 border border-green-200 rounded-lg p-4">
              <div className="flex">
                <Check className="h-5 w-5 text-green-400 mr-3 mt-0.5" />
                <div>
                  <h3 className="text-sm font-medium text-green-800">Import Successful!</h3>
                  <p className="text-sm text-green-700 mt-1">
                    Your FIO results have been processed and stored. Redirecting to dashboard...
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
