// frontend-vue/src/pages/UserManager.vue
<template>
  <div class="user-manager-page min-h-screen bg-gray-50 p-6">
    <div class="max-w-5xl mx-auto space-y-6">
      <header>
        <h1 class="text-3xl font-bold text-gray-900">User Management</h1>
        <p class="text-gray-600 mt-2">Create, update, and remove user accounts.</p>
      </header>

      <div v-if="!hasAdminAccess" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
        <h2 class="font-semibold">Access denied</h2>
        <p class="text-sm mt-1">Administrator privileges are required to manage users.</p>
      </div>

      <template v-else>
        <div v-if="loading" class="bg-white border border-gray-200 rounded-lg p-8 text-center">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p class="text-gray-600 mt-3">Loading users…</p>
        </div>

        <template v-else>
          <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
            {{ error }}
          </div>

          <div class="flex items-center justify-between bg-white border border-gray-200 rounded-lg px-4 py-3">
            <div class="text-sm text-gray-600">
              {{ users.length }} user{{ users.length === 1 ? '' : 's' }}
            </div>
            <button
              class="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              @click="openCreateForm"
            >
              Add User
            </button>
          </div>

          <div class="bg-white border border-gray-200 rounded-lg overflow-hidden">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Username</th>
                  <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Role</th>
                  <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <tr v-for="user in users" :key="user.username" class="hover:bg-gray-50">
                  <td class="px-6 py-4 text-sm font-medium text-gray-900">{{ user.username }}</td>
                  <td class="px-6 py-4 text-sm text-gray-600">
                    <span
                      :class="[
                        'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                        user.role === 'admin'
                          ? 'bg-purple-100 text-purple-800'
                          : 'bg-blue-100 text-blue-800'
                      ]"
                    >
                      {{ user.role === 'admin' ? 'Administrator' : 'Uploader' }}
                    </span>
                  </td>
                  <td class="px-6 py-4 text-right text-sm font-medium space-x-3">
                    <button
                      class="text-blue-600 hover:text-blue-800 disabled:opacity-50"
                      :disabled="saving || deleting[user.username]"
                      @click="openEditForm(user)"
                    >
                      Edit
                    </button>
                    <button
                      class="text-red-600 hover:text-red-800 disabled:opacity-50"
                      :disabled="saving || deleting[user.username] || user.username === currentUsername"
                      @click="handleDelete(user.username)"
                    >
                      {{ deleting[user.username] ? 'Deleting…' : 'Delete' }}
                    </button>
                  </td>
                </tr>
                <tr v-if="users.length === 0">
                  <td colspan="3" class="px-6 py-6 text-center text-sm text-gray-500">
                    No users found.
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>
      </template>
    </div>

    <!-- Modal -->
    <div
      v-if="showForm"
      class="fixed inset-0 bg-gray-900/50 flex items-center justify-center z-50"
    >
      <div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
        <div class="flex items-center justify-between mb-4">
          <h2 class="text-xl font-semibold text-gray-900">
            {{ isEditing ? 'Edit User' : 'Create User' }}
          </h2>
          <button class="text-gray-400 hover:text-gray-600" @click="closeForm">
            <span class="sr-only">Close</span>
            ×
          </button>
        </div>

        <form class="space-y-4" @submit.prevent="submitForm">
          <div>
            <label class="block text-sm font-medium text-gray-700">Username</label>
            <input
              v-model="formUsername"
              type="text"
              :disabled="isEditing"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 disabled:bg-gray-100"
            />
            <p v-if="formErrors.username" class="mt-1 text-sm text-red-600">{{ formErrors.username }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700">
              {{ isEditing ? 'New Password (optional)' : 'Password' }}
            </label>
            <input
              v-model="formPassword"
              type="password"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
              :placeholder="isEditing ? 'Leave blank to keep current password' : ''"
            />
            <p v-if="formErrors.password" class="mt-1 text-sm text-red-600">{{ formErrors.password }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700">Confirm Password</label>
            <input
              v-model="confirmPassword"
              type="password"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
              :placeholder="isEditing ? 'Leave blank to keep current password' : ''"
            />
            <p v-if="formErrors.confirmPassword" class="mt-1 text-sm text-red-600">{{ formErrors.confirmPassword }}</p>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700">Role</label>
            <select
              v-model="formRole"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
            >
              <option value="uploader">Uploader</option>
              <option value="admin">Administrator</option>
            </select>
          </div>

          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
              @click="closeForm"
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700 disabled:opacity-50"
              :disabled="saving"
            >
              {{ saving ? 'Saving…' : 'Save User' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { Api } from '@/services/api'
import { useAuth } from '@/composables/useAuth'

interface UserRow {
  username: string
  role: 'admin' | 'uploader'
}

const { user: currentUser, hasPermission } = useAuth()

const users = ref<UserRow[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
const showForm = ref(false)
const isEditing = ref(false)
const formUsername = ref('')
const formRole = ref<'admin' | 'uploader'>('uploader')
const formPassword = ref('')
const confirmPassword = ref('')
const formErrors = ref<Record<string, string>>({})
const saving = ref(false)
const deleting = ref<Record<string, boolean>>({})

const hasAdminAccess = computed(() => hasPermission('admin'))
const currentUsername = computed(() => currentUser.value?.username ?? '')

const resetForm = () => {
  showForm.value = false
  isEditing.value = false
  formUsername.value = ''
  formRole.value = 'uploader'
  formPassword.value = ''
  confirmPassword.value = ''
  formErrors.value = {}
}

const openCreateForm = () => {
  formUsername.value = ''
  formRole.value = 'uploader'
  formPassword.value = ''
  confirmPassword.value = ''
  formErrors.value = {}
  isEditing.value = false
  showForm.value = true
}

const openEditForm = (user: UserRow) => {
  formUsername.value = user.username
  formRole.value = user.role
  formPassword.value = ''
  confirmPassword.value = ''
  formErrors.value = {}
  isEditing.value = true
  showForm.value = true
}

const closeForm = () => {
  resetForm()
}

const validateForm = (editing: boolean): boolean => {
  const errors: Record<string, string> = {}

  if (!editing) {
    if (!formUsername.value.trim()) {
      errors.username = 'Username is required'
    } else if (!/^[a-zA-Z0-9_-]+$/.test(formUsername.value)) {
      errors.username = 'Use letters, numbers, hyphen, or underscore only'
    }
  }

  if (!editing || formPassword.value) {
    if (formPassword.value.length < 4) {
      errors.password = 'Password must be at least 4 characters'
    }
    if (formPassword.value !== confirmPassword.value) {
      errors.confirmPassword = 'Passwords do not match'
    }
  }

  formErrors.value = errors
  return Object.keys(errors).length === 0
}

const loadUsers = async () => {
  if (!hasAdminAccess.value) {
    users.value = []
    loading.value = false
    return
  }

  loading.value = true
  error.value = null
  try {
    const response = await Api.listUsers()
    users.value = response.map((user) => ({
      username: user.username,
      role: (user.role === 'admin' ? 'admin' : 'uploader') as 'admin' | 'uploader',
    }))
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load users'
  } finally {
    loading.value = false
  }
}

const submitForm = async () => {
  const editing = isEditing.value
  if (!validateForm(editing)) return

  saving.value = true
  error.value = null

  try {
    if (editing) {
      const payload: { password?: string; role?: 'admin' | 'uploader' } = {}
      if (formPassword.value) {
        payload.password = formPassword.value
      }
      if (formRole.value) {
        payload.role = formRole.value
      }
      await Api.updateUser(formUsername.value, payload)
    } else {
      await Api.createUser(formUsername.value.trim(), formPassword.value, formRole.value)
    }

    await loadUsers()
    resetForm()
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to save user'
  } finally {
    saving.value = false
  }
}

const handleDelete = async (username: string) => {
  if (username === currentUsername.value) {
    error.value = 'You cannot delete your own account.'
    return
  }

  if (!confirm(`Delete user "${username}"? This action cannot be undone.`)) {
    return
  }

  deleting.value = { ...deleting.value, [username]: true }
  error.value = null

  try {
    await Api.deleteUser(username)
    await loadUsers()
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to delete user'
  } finally {
    deleting.value = { ...deleting.value, [username]: false }
  }
}

onMounted(() => {
  if (hasAdminAccess.value) {
    loadUsers()
  } else {
    loading.value = false
  }
})

watch(hasAdminAccess, (canManage) => {
  if (canManage && !loading.value && users.value.length === 0) {
    loadUsers()
  }
})
</script>

<style scoped>
</style>

// frontend/src/pages/UserManager.tsx
/**
 * User Manager page - Admin interface for managing users
 */

import React, { useState, useEffect } from 'react';
import { User, getUsers, createUser, updateUser, deleteUser, UserCreate, UserUpdate } from '../services/api/users';
import { useAuth } from '../contexts/AuthContext';
import { DashboardHeader } from '../components/layout';

interface UserFormData {
	username: string;
	password: string;
	confirmPassword: string;
	role: 'admin' | 'uploader';
}

const UserManager: React.FC = () => {
	const { username: currentUsername, isAdmin } = useAuth();
	const [users, setUsers] = useState<User[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [showCreateForm, setShowCreateForm] = useState(false);
	const [editingUser, setEditingUser] = useState<User | null>(null);
	const [formData, setFormData] = useState<UserFormData>({
		username: '',
		password: '',
		confirmPassword: '',
		role: 'uploader'
	});
	const [formErrors, setFormErrors] = useState<Record<string, string>>({});
	const [operationLoading, setOperationLoading] = useState<Record<string, boolean>>({});

	// Redirect non-admin users
	if (!isAdmin) {
		return (
			<div className="min-h-screen theme-bg-secondary flex items-center justify-center">
				<div className="text-center">
					<h1 className="text-2xl font-bold theme-text-primary mb-4">Access Denied</h1>
					<p className="theme-text-secondary">You need admin privileges to access user management.</p>
				</div>
			</div>
		);
	}

	// Load users on component mount
	useEffect(() => {
		loadUsers();
	}, []);

	const loadUsers = async () => {
		try {
			setLoading(true);
			setError(null);
			const usersData = await getUsers();
			setUsers(usersData);
		} catch (err) {
			console.error('Failed to load users:', err);
			setError(err instanceof Error ? err.message : 'Failed to load users');
		} finally {
			setLoading(false);
		}
	};

	const resetForm = () => {
		setFormData({
			username: '',
			password: '',
			confirmPassword: '',
			role: 'uploader'
		});
		setFormErrors({});
		setShowCreateForm(false);
		setEditingUser(null);
	};

	const validateForm = (isEdit = false): boolean => {
		const errors: Record<string, string> = {};

		if (!isEdit && !formData.username.trim()) {
			errors.username = 'Username is required';
		} else if (!isEdit && !/^[a-zA-Z0-9_-]+$/.test(formData.username)) {
			errors.username = 'Username can only contain letters, numbers, hyphens, and underscores';
		}

		if (!isEdit || formData.password) {
			if (formData.password.length < 4) {
				errors.password = 'Password must be at least 4 characters';
			}
			if (formData.password !== formData.confirmPassword) {
				errors.confirmPassword = 'Passwords do not match';
			}
		}

		setFormErrors(errors);
		return Object.keys(errors).length === 0;
	};

	const handleCreateUser = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!validateForm()) return;

		const operationKey = 'create';
		setOperationLoading(prev => ({ ...prev, [operationKey]: true }));

		try {
			const userData: UserCreate = {
				username: formData.username.trim(),
				password: formData.password,
				role: formData.role
			};

			await createUser(userData);
			await loadUsers();
			resetForm();
		} catch (err) {
			console.error('Failed to create user:', err);
			setError(err instanceof Error ? err.message : 'Failed to create user');
		} finally {
			setOperationLoading(prev => ({ ...prev, [operationKey]: false }));
		}
	};

	const handleUpdateUser = async (e: React.FormEvent) => {
		e.preventDefault();
		if (!editingUser || !validateForm(true)) return;

		const operationKey = `edit-${editingUser.username}`;
		setOperationLoading(prev => ({ ...prev, [operationKey]: true }));

		try {
			const userData: UserUpdate = {
				role: formData.role
			};

			if (formData.password) {
				userData.password = formData.password;
			}

			await updateUser(editingUser.username, userData);
			await loadUsers();
			resetForm();
		} catch (err) {
			console.error('Failed to update user:', err);
			setError(err instanceof Error ? err.message : 'Failed to update user');
		} finally {
			setOperationLoading(prev => ({ ...prev, [operationKey]: false }));
		}
	};

	const handleDeleteUser = async (username: string) => {
		if (!confirm(`Are you sure you want to delete user "${username}"?`)) return;

		const operationKey = `delete-${username}`;
		setOperationLoading(prev => ({ ...prev, [operationKey]: true }));

		try {
			await deleteUser(username);
			await loadUsers();
		} catch (err) {
			console.error('Failed to delete user:', err);
			setError(err instanceof Error ? err.message : 'Failed to delete user');
		} finally {
			setOperationLoading(prev => ({ ...prev, [operationKey]: false }));
		}
	};

	const startEditUser = (user: User) => {
		setEditingUser(user);
		setFormData({
			username: user.username,
			password: '',
			confirmPassword: '',
			role: user.role
		});
		setFormErrors({});
		setShowCreateForm(false);
	};

	if (loading) {
		return (
			<div className="min-h-screen theme-bg-secondary flex items-center justify-center">
				<div className="text-center">
					<div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
					<p className="theme-text-secondary">Loading users...</p>
				</div>
			</div>
		);
	}

	return (
		<div className="min-h-screen theme-bg-secondary">
			<DashboardHeader />
			<div className="py-8">
				<div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
					{/* Header */}
					<div className="mb-8">
						<h1 className="text-3xl font-bold theme-text-primary">User Management</h1>
						<p className="mt-2 text-sm theme-text-secondary">
							Manage admin and uploader users for the FIO Analyzer system.
						</p>
					</div>

					{/* Error Message */}
					{error && (
						<div className="mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-4">
							<div className="flex">
								<div className="flex-shrink-0">
									<svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
										<path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
									</svg>
								</div>
								<div className="ml-3">
									<h3 className="text-sm font-medium text-red-800 dark:text-red-200">Error</h3>
									<div className="mt-2 text-sm text-red-700 dark:text-red-300">{error}</div>
								</div>
								<div className="ml-auto pl-3">
									<button
										onClick={() => setError(null)}
										className="inline-flex text-red-400 hover:text-red-600 dark:hover:text-red-300"
									>
										<svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
											<path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
										</svg>
									</button>
								</div>
							</div>
						</div>
					)}

					{/* Actions */}
					<div className="mb-6 flex justify-between items-center">
						<div className="flex space-x-4">
							<button
								onClick={() => setShowCreateForm(true)}
								className="theme-btn-primary px-4 py-2 rounded-md transition-colors"
							>
								Add User
							</button>
							<button
								onClick={loadUsers}
								className="theme-btn-secondary px-4 py-2 rounded-md transition-colors"
							>
								Refresh
							</button>
						</div>
					</div>

					{/* Create/Edit User Form */}
					{(showCreateForm || editingUser) && (
						<div className="mb-8 theme-card shadow rounded-lg p-6">
						<h2 className="text-lg font-medium theme-text-primary mb-4">
							{editingUser ? `Edit User: ${editingUser.username}` : 'Create New User'}
						</h2>
						<form onSubmit={editingUser ? handleUpdateUser : handleCreateUser}>
							<div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
								{/* Username (only for create) */}
								{!editingUser && (
									<div>
										<label htmlFor="username" className="block text-sm font-medium theme-text-primary">
											Username
										</label>
										<input
											type="text"
											id="username"
											value={formData.username}
											onChange={(e) => setFormData(prev => ({ ...prev, username: e.target.value }))}
											className={`mt-1 block w-full border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 theme-bg-card theme-text-primary ${
												formErrors.username ? 'border-red-300' : 'theme-border'
											}`}
											placeholder="Enter username"
										/>
										{formErrors.username && (
											<p className="mt-1 text-sm text-red-600">{formErrors.username}</p>
										)}
									</div>
								)}

								{/* Role */}
								<div>
									<label htmlFor="role" className="block text-sm font-medium theme-text-primary">
										Role
									</label>
									<select
										id="role"
										value={formData.role}
										onChange={(e) => setFormData(prev => ({ ...prev, role: e.target.value as 'admin' | 'uploader' }))}
										className="mt-1 block w-full border theme-border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 theme-bg-card theme-text-primary"
										disabled={editingUser?.username === currentUsername} // Can't change your own role
									>
										<option value="uploader">Uploader</option>
										<option value="admin">Admin</option>
									</select>
									{editingUser?.username === currentUsername && (
										<p className="mt-1 text-sm theme-text-secondary">You cannot change your own role</p>
									)}
								</div>

								{/* Password */}
								<div>
									<label htmlFor="password" className="block text-sm font-medium theme-text-primary">
										{editingUser ? 'New Password (leave blank to keep current)' : 'Password'}
									</label>
									<input
										type="password"
										id="password"
										value={formData.password}
										onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
										className={`mt-1 block w-full border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 theme-bg-card theme-text-primary ${
											formErrors.password ? 'border-red-300' : 'theme-border'
										}`}
										placeholder={editingUser ? "Enter new password" : "Enter password"}
									/>
									{formErrors.password && (
										<p className="mt-1 text-sm text-red-600">{formErrors.password}</p>
									)}
								</div>

								{/* Confirm Password */}
								<div>
									<label htmlFor="confirmPassword" className="block text-sm font-medium theme-text-primary">
										Confirm Password
									</label>
									<input
										type="password"
										id="confirmPassword"
										value={formData.confirmPassword}
										onChange={(e) => setFormData(prev => ({ ...prev, confirmPassword: e.target.value }))}
										className={`mt-1 block w-full border rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 theme-bg-card theme-text-primary ${
											formErrors.confirmPassword ? 'border-red-300' : 'theme-border'
										}`}
										placeholder="Confirm password"
									/>
									{formErrors.confirmPassword && (
										<p className="mt-1 text-sm text-red-600">{formErrors.confirmPassword}</p>
									)}
								</div>
							</div>

							{/* Form Actions */}
							<div className="mt-6 flex justify-end space-x-3">
								<button
									type="button"
									onClick={resetForm}
									className="theme-btn-secondary px-4 py-2 rounded-md transition-colors"
								>
									Cancel
								</button>
								<button
									type="submit"
									disabled={operationLoading[editingUser ? `edit-${editingUser.username}` : 'create']}
									className="theme-btn-primary px-4 py-2 rounded-md transition-colors disabled:opacity-50"
								>
									{operationLoading[editingUser ? `edit-${editingUser.username}` : 'create'] && (
										<span className="inline-block animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></span>
									)}
									{editingUser ? 'Update User' : 'Create User'}
								</button>
							</div>
						</form>
						</div>
					)}

					{/* Users List */}
					<div className="theme-card shadow rounded-lg overflow-hidden">
						<div className="px-6 py-4 border-b theme-border">
							<h2 className="text-lg font-medium theme-text-primary">Users ({users.length})</h2>
						</div>
						<div className="divide-y theme-border">
							{users.length === 0 ? (
								<div className="px-6 py-8 text-center theme-text-secondary">
									No users found.
								</div>
							) : (
								users.map((user) => (
									<div key={user.username} className="px-6 py-4 flex items-center justify-between theme-bg-card">
									<div className="flex items-center">
										<div>
											<div className="flex items-center">
												<h3 className="text-sm font-medium theme-text-primary">{user.username}</h3>
												{user.username === currentUsername && (
													<span className="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200">
														You
													</span>
												)}
											</div>
											<p className="text-sm theme-text-secondary">
												Role: <span className={`font-medium ${
													user.role === 'admin' ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400'
												}`}>
													{user.role}
												</span>
											</p>
										</div>
									</div>
									<div className="flex items-center space-x-2">
										<button
											onClick={() => startEditUser(user)}
											className="text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300 text-sm font-medium transition-colors"
										>
											Edit
										</button>
										<button
											onClick={() => handleDeleteUser(user.username)}
											disabled={user.username === currentUsername || operationLoading[`delete-${user.username}`]}
											className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300 text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
										>
											{operationLoading[`delete-${user.username}`] && (
												<span className="inline-block animate-spin rounded-full h-3 w-3 border-b border-red-600 mr-1"></span>
											)}
											Delete
										</button>
									</div>
								</div>
								))
							)}
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default UserManager;
