// frontend-vue/src/components/ui/Modal.vue
<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-opacity duration-300"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition-opacity duration-200"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <!-- Backdrop -->
      <div
        v-if="isOpen"
        class="fixed inset-0 z-40 overflow-y-auto"
        :class="backdropClasses"
        @click.self="handleBackdropClick"
      >
        <div class="flex min-h-screen items-center justify-center p-4">
          <Transition
            enter-active-class="transition-all duration-300"
            enter-from-class="opacity-0 scale-95 translate-y-4"
            enter-to-class="opacity-100 scale-100 translate-y-0"
            leave-active-class="transition-all duration-200"
            leave-from-class="opacity-100 scale-100 translate-y-0"
            leave-to-class="opacity-0 scale-95 translate-y-4"
          >
            <!-- Modal content -->
            <div
              v-if="isOpen"
              ref="modalRef"
              class="relative w-full max-w-lg transform overflow-hidden rounded-lg bg-white shadow-xl transition-all dark:bg-gray-800"
              :class="modalClasses"
              role="dialog"
              aria-modal="true"
              :aria-labelledby="titleId"
              @keydown.escape="handleEscape"
            >
              <!-- Header -->
              <div
                v-if="title || $slots.header"
                class="flex items-center justify-between border-b border-gray-200 px-6 py-4 dark:border-gray-700"
              >
                <div :id="titleId" class="text-lg font-medium text-gray-900 dark:text-white">
                  <slot name="header">
                    {{ title }}
                  </slot>
                </div>

                <button
                  v-if="closable"
                  @click="close"
                  class="text-gray-400 hover:text-gray-600 dark:text-gray-500 dark:hover:text-gray-300"
                  aria-label="Close modal"
                >
                  <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <!-- Body -->
              <div class="px-6 py-4">
                <slot>
                  {{ content }}
                </slot>
              </div>

              <!-- Footer -->
              <div
                v-if="$slots.footer || showDefaultActions"
                class="flex items-center justify-end space-x-3 border-t border-gray-200 bg-gray-50 px-6 py-4 dark:border-gray-700 dark:bg-gray-800"
              >
                <slot name="footer">
                  <div v-if="showDefaultActions" class="flex space-x-3">
                    <button
                      @click="close"
                      class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-600"
                    >
                      {{ cancelText }}
                    </button>

                    <button
                      @click="confirm"
                      class="inline-flex justify-center px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                      :class="confirmButtonClasses"
                    >
                      {{ confirmText }}
                    </button>
                  </div>
                </slot>
              </div>
            </div>
          </Transition>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'

type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full'

interface Props {
  modelValue: boolean
  title?: string
  content?: string
  size?: ModalSize
  closable?: boolean
  backdropClosable?: boolean
  confirmText?: string
  cancelText?: string
  showDefaultActions?: boolean
  confirmVariant?: 'primary' | 'danger'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
  closable: true,
  backdropClosable: true,
  confirmText: 'Confirm',
  cancelText: 'Cancel',
  showDefaultActions: false,
  confirmVariant: 'primary',
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  confirm: []
  cancel: []
  close: []
}>()

const modalRef = ref<HTMLElement>()
const titleId = ref(`modal-title-${Math.random().toString(36).substr(2, 9)}`)

const isOpen = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
})

const modalClasses = computed(() => {
  const sizeClasses = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-xl',
    full: 'max-w-4xl',
  }

  return sizeClasses[props.size] || sizeClasses.md
})

const backdropClasses = computed(() => {
  return 'bg-gray-500 bg-opacity-75 dark:bg-gray-900 dark:bg-opacity-75'
})

const confirmButtonClasses = computed(() => {
  const variantClasses = {
    primary: 'bg-blue-600 hover:bg-blue-700 focus:ring-blue-500',
    danger: 'bg-red-600 hover:bg-red-700 focus:ring-red-500',
  }

  return variantClasses[props.confirmVariant] || variantClasses.primary
})

function open() {
  isOpen.value = true
}

function close() {
  isOpen.value = false
  emit('close')
}

function confirm() {
  emit('confirm')
  close()
}

function cancel() {
  emit('cancel')
  close()
}

function handleBackdropClick() {
  if (props.backdropClosable) {
    close()
  }
}

function handleEscape(event: KeyboardEvent) {
  if (event.key === 'Escape' && props.closable) {
    close()
  }
}

// Focus management
function trapFocus(event: KeyboardEvent) {
  if (!modalRef.value) return

  const focusableElements = modalRef.value.querySelectorAll(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
  )

  const firstElement = focusableElements[0] as HTMLElement
  const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement

  if (event.key === 'Tab') {
    if (event.shiftKey) {
      if (document.activeElement === firstElement) {
        event.preventDefault()
        lastElement.focus()
      }
    } else {
      if (document.activeElement === lastElement) {
        event.preventDefault()
        firstElement.focus()
      }
    }
  }
}

watch(isOpen, (newValue) => {
  if (newValue) {
    // Store the currently focused element
    const focusedElement = document.activeElement as HTMLElement

    // Focus the modal
    nextTick(() => {
      modalRef.value?.focus()

      // Add event listeners
      document.addEventListener('keydown', trapFocus)
    })

    // Store reference for cleanup
    modalRef.value?._focusedElement = focusedElement
  } else {
    // Restore focus
    const focusedElement = modalRef.value?._focusedElement as HTMLElement
    if (focusedElement) {
      focusedElement.focus()
    }

    // Remove event listeners
    document.removeEventListener('keydown', trapFocus)
  }
})

onMounted(() => {
  if (isOpen.value) {
    document.addEventListener('keydown', trapFocus)
  }
})

onUnmounted(() => {
  document.removeEventListener('keydown', trapFocus)
})

// Prevent body scroll when modal is open
watch(isOpen, (newValue) => {
  if (newValue) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
})

// Cleanup on unmount
onUnmounted(() => {
  document.body.style.overflow = ''
})
</script>

<style scoped>
/* Additional styles if needed */
</style>

// frontend/src/components/ui/Modal.tsx
// Reusable Modal component
import React, { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
import Button from './Button';

export interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    title?: string;
    children: React.ReactNode;
    size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
    showCloseButton?: boolean;
    closeOnOverlayClick?: boolean;
    closeOnEscape?: boolean;
    footer?: React.ReactNode;
    className?: string;
}

const Modal: React.FC<ModalProps> = ({
    isOpen,
    onClose,
    title,
    children,
    size = 'md',
    showCloseButton = true,
    closeOnOverlayClick = true,
    closeOnEscape = true,
    footer,
    className = '',
}) => {
    const modalRef = useRef<HTMLDivElement>(null);

    const sizeClasses = {
        sm: 'max-w-md',
        md: 'max-w-lg',
        lg: 'max-w-2xl',
        xl: 'max-w-4xl',
        full: 'max-w-full mx-4',
    };

    // Handle escape key
    useEffect(() => {
        if (!isOpen || !closeOnEscape) return;

        const handleEscape = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                onClose();
            }
        };

        document.addEventListener('keydown', handleEscape);
        return () => document.removeEventListener('keydown', handleEscape);
    }, [isOpen, closeOnEscape, onClose]);

    // Handle body scroll lock
    useEffect(() => {
        if (isOpen) {
            document.body.style.overflow = 'hidden';
        } else {
            document.body.style.overflow = '';
        }

        return () => {
            document.body.style.overflow = '';
        };
    }, [isOpen]);

    // Focus management
    useEffect(() => {
        if (isOpen && modalRef.current) {
            modalRef.current.focus();
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const handleOverlayClick = (event: React.MouseEvent) => {
        if (closeOnOverlayClick && event.target === event.currentTarget) {
            onClose();
        }
    };

    return (
        <div className="fixed inset-0 z-50 overflow-y-auto">
            <div 
                className="flex min-h-screen items-center justify-center p-4"
                onClick={handleOverlayClick}
            >
                {/* Backdrop */}
                <div className="fixed inset-0 bg-black bg-opacity-50 transition-opacity" />
                
                {/* Modal */}
                <div
                    ref={modalRef}
                    className={`relative w-full ${sizeClasses[size]} transform rounded-lg bg-white shadow-xl transition-all theme-card ${className}`}
                    tabIndex={-1}
                >
                    {/* Header */}
                    {(title || showCloseButton) && (
                        <div className="flex items-center justify-between border-b px-6 py-4 theme-border-primary">
                            {title && (
                                <h2 className="text-lg font-semibold theme-text-primary">
                                    {title}
                                </h2>
                            )}
                            {showCloseButton && (
                                <button
                                    onClick={onClose}
                                    className="text-gray-400 hover:text-gray-600 transition-colors theme-text-secondary hover:theme-text-primary"
                                >
                                    <X size={20} />
                                </button>
                            )}
                        </div>
                    )}

                    {/* Body */}
                    <div className="px-6 py-4">
                        {children}
                    </div>

                    {/* Footer */}
                    {footer && (
                        <div className="border-t px-6 py-4 bg-gray-50 rounded-b-lg theme-bg-secondary theme-border-primary">
                            {footer}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

// Confirmation modal
export interface ConfirmModalProps {
    isOpen: boolean;
    onClose: () => void;
    onConfirm: () => void;
    title: string;
    message: string;
    confirmText?: string;
    cancelText?: string;
    variant?: 'danger' | 'warning' | 'info';
    loading?: boolean;
}

export const ConfirmModal: React.FC<ConfirmModalProps> = ({
    isOpen,
    onClose,
    onConfirm,
    title,
    message,
    confirmText = 'Confirm',
    cancelText = 'Cancel',
    variant = 'info',
    loading = false,
}) => {
    const confirmVariant = variant === 'danger' ? 'danger' : 'primary';

    const footer = (
        <div className="flex justify-end space-x-3">
            <Button
                variant="outline"
                onClick={onClose}
                disabled={loading}
            >
                {cancelText}
            </Button>
            <Button
                variant={confirmVariant}
                onClick={onConfirm}
                loading={loading}
            >
                {confirmText}
            </Button>
        </div>
    );

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            title={title}
            size="sm"
            footer={footer}
            closeOnOverlayClick={!loading}
            closeOnEscape={!loading}
        >
            <p className="theme-text-secondary">
                {message}
            </p>
        </Modal>
    );
};

// Modal hooks for imperative usage
export const useModal = () => {
    const [isOpen, setIsOpen] = React.useState(false);

    const open = React.useCallback(() => setIsOpen(true), []);
    const close = React.useCallback(() => setIsOpen(false), []);
    const toggle = React.useCallback(() => setIsOpen(prev => !prev), []);

    return {
        isOpen,
        open,
        close,
        toggle,
    };
};

// Modal context for nested modals
interface ModalContextValue {
    openModals: number;
    registerModal: () => void;
    unregisterModal: () => void;
}

const ModalContext = React.createContext<ModalContextValue>({
    openModals: 0,
    registerModal: () => {},
    unregisterModal: () => {},
});

export const ModalProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [openModals, setOpenModals] = React.useState(0);

    const registerModal = React.useCallback(() => {
        setOpenModals(prev => prev + 1);
    }, []);

    const unregisterModal = React.useCallback(() => {
        setOpenModals(prev => Math.max(0, prev - 1));
    }, []);

    return (
        <ModalContext.Provider value={{ openModals, registerModal, unregisterModal }}>
            {children}
        </ModalContext.Provider>
    );
};

export const useModalContext = () => React.useContext(ModalContext);

export default Modal;
